# TODO: Translation updated at 2019-08-20 22:41

translate english strings:

    # game/options.rpy:30
    old "Little Slice Of My Life"
    new "Little Slice Of My Life"

    # game/options.rpy:47
    old "Game ini dikembangkan oleh Muhammad \"Hakase\" Hamdani. Sebagai bagian dari langkah awal menggunakan Ren'Py.\n\nLemma Soft Forums: NotReality_\n\nWattpad: {a=https://www.wattpad.com/user/Penghayal_Pasif}Penghayal_Pasif{/a}\n\nGmail: mhdhamdani.formal@gmail.com\n\n\n\n\n\nSprite Amanda: Elzee\n\nBackground Art: Mugenjohncel\n\n\n\n\n\n\n\nSemua cerita disini hanyalah fiksi belaka. Jika ada kesamaan nama tokoh, tempat, atau kejadian maka itu hanya ketidaksengajaan belaka.\n\n\n\n"
    new "This game is developed by Muhammad \"Hakase\" Hamdani. As part of first step in using Ren'Py.\n\nLemma Soft Forums: NotReality_\n\nWattpad: {a=https://www.wattpad.com/user/Penghayal_Pasif}Penghayal_Pasif{/a}\n\nGmail: mhdhamdani.formal@gmail.com\n\n\n\n\n\nSprite Amanda: Elzee\n\nBackground Art: Mugenjohncel\n\n\n\n\n\n\n\nAll the stories here are mere fiction. If there are similarities in the names of characters, places, or events, then it is just an accident."

    # game/options.rpy:69
    old "Software ini dilindungi oleh beberapa lisensi terpisah. Ada dua lisensi untuk gambar yang digunakan, dan satu lisensi untuk software itu sendiri, untuk selengkapnya bisa dilihat di bawah. Perlu diingat bawha lisensi yang akan ditampilkan berbahasa Inggris.\n\nThis software is protected under several seperated licenses. There's two licenses for the pictures, and one license for the software itself. For details can be seen below.\n\n\n\n\n\nLittle Slice Of My Life\n\nLittle Slice Of My Life is licensed under GNU GPL v3:\n\nThis program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\n\n\nSprite Lisa by Elzee\n\nThis sprite set is released under the following license: Creative Commons Attribution-NonCommercial-ShareAlike\n\nYou are free to:\n\nShare — copy and redistribute the material in any medium or format\n\nAdapt — remix, transform, and build upon the material\n\nThe licensor cannot revoke these freedoms as long as you follow the license terms.\n\nUnder the following terms:\n\nAttribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.\n\nNonCommercial — You may not use the material for commercial purposes.\n\nNo additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.\n\n\n\nBackground by Mugenjohncel\n\nTerms of usage, as copied from {a=https://lemmasoft.renai.us/forums/viewtopic.php?t=17302} UNCLE MUGEN'S FREE VN (OELVN) RESOURCES{/a}:\n\n▪ Feel free to use for whatever purpose it may serve best.\n\n▪ OK for both Commercial and Free projects.\n\n▪ Modifications are OK and highly encouraged.\n\n▪ Not really required but I really do appreciate if you could tell me you have a project using these free resources.\n\n▪ TLDR: Just take them... no strings attached..."
    new "This software is protected by several separate licenses. There are two licenses for the images used, and one license for the software itself, for details can be seen below. Keep in mind that the license will be displayed in English.\n\n\n\n\n\nLittle Slice Of My Life\n\nLittle Slice Of My Life is licensed under GNU GPL v3:\n\nThis program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with this program.  If not, see <https://www.gnu.org/licenses/>.\n\n\n\nSprite Lisa by Elzee\n\nThis sprite set is released under the following license: Creative Commons Attribution-NonCommercial-ShareAlike\n\nYou are free to:\n\nShare — copy and redistribute the material in any medium or format\n\nAdapt — remix, transform, and build upon the material\n\nThe licensor cannot revoke these freedoms as long as you follow the license terms.\n\nUnder the following terms:\n\nAttribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.\n\nNonCommercial — You may not use the material for commercial purposes.\n\nNo additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.\n\n\n\nBackground by Mugenjohncel\n\nTerms of usage, as copied from {a=https://lemmasoft.renai.us/forums/viewtopic.php?t=17302} UNCLE MUGEN'S FREE VN (OELVN) RESOURCES{/a}:\n\n▪ Feel free to use for whatever purpose it may serve best.\n\n▪ OK for both Commercial and Free projects.\n\n▪ Modifications are OK and highly encouraged.\n\n▪ Not really required but I really do appreciate if you could tell me you have a project using these free resources.\n\n▪ TLDR: Just take them... no strings attached..."
